### ISSUE TITLE
Allow Image Extensions

### ISSUE THREAD

**Issue by browniefed** [kentcdodds/mdx-bundler#16]
- `mdx-bundler` version: 3.1.2
- `node` version: 14.9
- `npm` version: yarn

Relevant code or config

```js
import { D3JS } from "@/lib/technologies";

export const meta = {
  title:
    "Add Interactivity to a Line Graph using scaleLinear.invert to Find a Data Point to Highlight on Mouse Move",
  description:
    "",
  type: "TUTORIAL",
  createdAt: "2018-03-20T01:58:20.594+00:00",
  technology: D3JS,
  tags: [],
  images: [require("./highlighted.png")],
};

```

What you did: 

Attempted to add a plugin to resolve
Attempted to supply to `files`

What happened:
When supplied to files as a string
```
__mdx_bundler_fake_dir__/index.mdx:16:19: error: [JavaScript plugins] Invalid loader: "png" (valid: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary)
```

Problem description:

In my MDX rather than using `frontmatter` I leverage a meta export, along with `next-images` + https://github.com/sergioramos/remark-copy-linked-files

This allows me to colocate all the things next to each other, and then they are processed into Next.js public directory and such.

However mdx-bunlder doesn't let unknown files types fall through to potentially get resolved by a appended plugin

Suggested solution:

I don't know?

Add in an optional way for unknown extensions to fall through to a future resolver?

**Comment by kentcdodds** [comment]
Hi there @browniefed!

I don't know whether esbuild supports this (which is why you get the failure, there's no loader for that type), but if there's an esbuild plugin you'd like to add you have complete control over the esbuild config.

Alternatively, you can use an older version of mdx-bundler which uses rollup. It's not nearly as fast as esbuild, but it should support more plugins and things.

As it is, there's nothing we can do within mdx-bundler to support image files, so I'm going to close this.

FWIW, I'm moving to uploading all my images to cloudinary and referencing them that way. There are a lot of benefits to this approach (no need to reprocess the same image every single time you need to build/compile for one). That's what I'd personally recommend (yes, I know it's nice to have the images colocated, but I don't think it's worth giving up the benefits of moving it to a service like cloudinary).

**Comment by browniefed** [comment]
It's totally possible https://esbuild.github.io/content-types/#external-file

I think I just wasn't sure if 

```
      options.plugins = [myCustomplugin, ...options.plugins];
```
Was kosher or if I had to do

```
      options.plugins = [...options.plugins, myCustomplugin];
```

But overall sounds like I think I can do the `myCustomPlugin` before `mdx-bundler` does it stuff.

I don't do any build time optimizations. I leverage `next/image` so basically just copying files.

**Comment by kentcdodds** [comment]
Ah cool 👍 do you mind adding your solution to the README? I imagine you won't be the first who wants this.

**Comment by browniefed** [comment]
Still trying to solve it ha. Think a deeper dive into rebuild docs is
required. But when I get a solution I'll post it

**Comment by deadcoder0904** [comment]
@browniefed did you get around solving it?

**Comment by browniefed** [comment]
@deadcoder0904 it is supported now if you look here

https://github.com/kentcdodds/mdx-bundler#image-bundling

**Comment by browniefed** [comment]
I think for image imports I ended up pre parsing from the document because in most cases it was in front matter then the remark image solution handles it for body images

**Comment by deadcoder0904** [comment]
Hahah, I'm just reading that thing for last couple of hours. I thought it's different if it's used in `frontmatter` vs the actual body but it looks like its the same.
